eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8766
userName: '{cipher}aec6bfa7104805ad820aefe126d7bc10c273b4b3a0ceb2887817249607fc9d5d'
spring:
  application:
    name: eurekaclient
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:9411